### ISSUE TITLE
환경 정보 취득 기능 코드보완

### ISSUE THREAD

**Issue by miho030** [BoB10-SEDR/Agent#15]
* 환경 정보 취득 기능 코드 보완

프로토타입 코드내 기존 구현한 2개 기능에 대한 코드 재구성

- 네트워크 어댑터 정보 획득
- 장비 서비스 목록 정보 획득

**Comment by npclown** [comment]
@miho030 pcap 오류 및 class 형태 코드 재조정 완료

**Comment by miho030** [comment]
변경된 코드 확인 이후,
테스트 결과 Raspberry Pi model 3 에서 정상 작동하는 것 확인했습니다.

감사합니다.
