### ISSUE TITLE
장비 모델명과 시리얼 넘버 출력안되는 현상

### ISSUE THREAD

**Issue by npclown** [BoB10-SEDR/Agent#22]
Device modelName 과 Device SerialNum이 출력이 제대로 되지 않는 현상이 발견되었다. 

리눅스 명령어를 사용하여 cat /proc/cpuinfo | grep Model 또는 cat /proc/cpuinfo | grep Serial 으로 조회를 수행하던데, vmware로 구축된 환경에서 cat /proc/cpuinfo를 조회하면 Model 과 Serial이 존재하지 않는다 

여기에 대한 확인 필요

![image](https://user-images.githubusercontent.com/29626700/138551056-352bdf40-fa5a-498c-b872-52c1871c64fc.png)

**Comment by miho030** [comment]
### (장비 모델명과 시리얼 넘버 출력안되는 현상) 에 대한 답변

- 테스트 환경의 차이점 : 가상환경(vmware)/실제 물리환경(Raspberry model 3)

차이점을 보면 두 결과간의 차이가 가상환경인지, 실제 물리적인 보드에서 동작하는 것인지를 알 수 있다.
또한 이 차이로 인해 결과가 다르게 나온다는 점을 인지한 상태로 생각해본다면, 가상환경에서는 장비의 모델명과 hwid(장비 보드에 대한 시리얼 번호)를 못가져온다는 논리적인 결과에 도달할 수 있다.

하지만 이 결론이 진실된 것인지에 대해서는 cpuinfo가 작동하는 원리에 대해 살펴보면 알 수 있다.

* * *
### cat /proc/cpuinfo를 수행하였을 때 일어나는 일

/proc/cpuinfo에 저장된 데이터를 찾아오는 주체는 "procfs"라는 기능이며, 이 기능은 로컬 환경에서 파일시스템(디스크, 이동식 메모리), 네트워크 로부터 데이터를 받아오지 않는다. 기존 초기 리눅스 모델에서는 procfs를 통해 얻은 정보를 파일로 저장하여 보관하고, 이를 cpuinfo에 취합하는 형태로 구현되었었지만 현재 대부분의 리눅스 배포판은 /proc/bus 를 통해
직접 장비의 버스 인터페이스에 접근하여 정보를 받아오는 형태로 진화하였다.

* * *
### 결론
가상 환경은 실제 물리적인 보드가 없기 때문에, procfs가 /proc/bus를 통해 
장비의 보드에서 버스 인터페이스에 접근할 수 없기 때문에 시리얼 번호화 모델명을 받아오지 못한 것으로 이해할 수 있다.


참조 : https://unix.stackexchange.com/questions/121702/what-happens-when-i-run-the-command-cat-proc-cpuinfo
